//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccommodationAccessEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccommodationAccessEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="freeSeating"/>
 *     &lt;enumeration value="reservation"/>
 *     &lt;enumeration value="standing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AccommodationAccessEnumeration")
@XmlEnum
public enum AccommodationAccessEnumeration {

    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("freeSeating")
    FREE_SEATING("freeSeating"),

    /**
     * pti23_3
     * 
     */
    @XmlEnumValue("reservation")
    RESERVATION("reservation"),
    @XmlEnumValue("standing")
    STANDING("standing");
    private final String value;

    AccommodationAccessEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccommodationAccessEnumeration fromValue(String v) {
        for (AccommodationAccessEnumeration c: AccommodationAccessEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
