//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllModesEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AllModesEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="air"/>
 *     &lt;enumeration value="bus"/>
 *     &lt;enumeration value="trolleyBus"/>
 *     &lt;enumeration value="tram"/>
 *     &lt;enumeration value="coach"/>
 *     &lt;enumeration value="rail"/>
 *     &lt;enumeration value="intercityRail"/>
 *     &lt;enumeration value="urbanRail"/>
 *     &lt;enumeration value="metro"/>
 *     &lt;enumeration value="water"/>
 *     &lt;enumeration value="cableway"/>
 *     &lt;enumeration value="funicular"/>
 *     &lt;enumeration value="taxi"/>
 *     &lt;enumeration value="selfDrive"/>
 *     &lt;enumeration value="foot"/>
 *     &lt;enumeration value="bicycle"/>
 *     &lt;enumeration value="motorcycle"/>
 *     &lt;enumeration value="car"/>
 *     &lt;enumeration value="shuttle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AllModesEnumeration")
@XmlEnum
public enum AllModesEnumeration {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("air")
    AIR("air"),
    @XmlEnumValue("bus")
    BUS("bus"),
    @XmlEnumValue("trolleyBus")
    TROLLEY_BUS("trolleyBus"),
    @XmlEnumValue("tram")
    TRAM("tram"),
    @XmlEnumValue("coach")
    COACH("coach"),
    @XmlEnumValue("rail")
    RAIL("rail"),
    @XmlEnumValue("intercityRail")
    INTERCITY_RAIL("intercityRail"),
    @XmlEnumValue("urbanRail")
    URBAN_RAIL("urbanRail"),
    @XmlEnumValue("metro")
    METRO("metro"),
    @XmlEnumValue("water")
    WATER("water"),
    @XmlEnumValue("cableway")
    CABLEWAY("cableway"),
    @XmlEnumValue("funicular")
    FUNICULAR("funicular"),
    @XmlEnumValue("taxi")
    TAXI("taxi"),

    /**
     * See pti12_x.
     * 
     */
    @XmlEnumValue("selfDrive")
    SELF_DRIVE("selfDrive"),
    @XmlEnumValue("foot")
    FOOT("foot"),
    @XmlEnumValue("bicycle")
    BICYCLE("bicycle"),
    @XmlEnumValue("motorcycle")
    MOTORCYCLE("motorcycle"),
    @XmlEnumValue("car")
    CAR("car"),
    @XmlEnumValue("shuttle")
    SHUTTLE("shuttle");
    private final String value;

    AllModesEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AllModesEnumeration fromValue(String v) {
        for (AllModesEnumeration c: AllModesEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
