//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CateringServiceEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CateringServiceEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bar"/>
 *     &lt;enumeration value="beverageVendingMachine"/>
 *     &lt;enumeration value="buffet"/>
 *     &lt;enumeration value="coffeeShop"/>
 *     &lt;enumeration value="firstClassRestaurant"/>
 *     &lt;enumeration value="foodVendingMachine"/>
 *     &lt;enumeration value="hotFoodService"/>
 *     &lt;enumeration value="restaurant"/>
 *     &lt;enumeration value="snacks"/>
 *     &lt;enumeration value="trolleyService"/>
 *     &lt;enumeration value="noBeveragesAvailable"/>
 *     &lt;enumeration value="noFoodServiceAvailable"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CateringServiceEnumeration")
public enum CateringServiceEnumeration {

    BAR("bar"),
    BEVERAGE_VENDING_MACHINE("beverageVendingMachine"),
    BUFFET("buffet"),
    COFFEE_SHOP("coffeeShop"),
    FIRST_CLASS_RESTAURANT("firstClassRestaurant"),
    FOOD_VENDING_MACHINE("foodVendingMachine"),
    HOT_FOOD_SERVICE("hotFoodService"),
    RESTAURANT("restaurant"),
    SNACKS("snacks"),
    TROLLEY_SERVICE("trolleyService"),
    NO_BEVERAGES_AVAILABLE("noBeveragesAvailable"),
    NO_FOOD_SERVICE_AVAILABLE("noFoodServiceAvailable"),
    OTHER("other");
    private final String value;

    CateringServiceEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CateringServiceEnumeration fromValue(String v) {
        for (CateringServiceEnumeration c: CateringServiceEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
