//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CycleStorageEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CycleStorageEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="racks"/>
 *     &lt;enumeration value="bars"/>
 *     &lt;enumeration value="railings"/>
 *     &lt;enumeration value="cycleScheme"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CycleStorageEnumeration")
@XmlEnum
public enum CycleStorageEnumeration {

    @XmlEnumValue("racks")
    RACKS("racks"),
    @XmlEnumValue("bars")
    BARS("bars"),
    @XmlEnumValue("railings")
    RAILINGS("railings"),
    @XmlEnumValue("cycleScheme")
    CYCLE_SCHEME("cycleScheme"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    CycleStorageEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CycleStorageEnumeration fromValue(String v) {
        for (CycleStorageEnumeration c: CycleStorageEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
