//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a list of objects.
 * 
 * <p>Java class for dataObjects_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataObjects_RelStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.netex.org.uk/netex}CompositeFrame"/>
 *         &lt;element ref="{http://www.netex.org.uk/netex}CommonFrame"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataObjects_RelStructure", propOrder = {
    "compositeFrameOrCommonFrame"
})
public class DataObjects_RelStructure {

    @XmlElements({
        @XmlElement(name = "CompositeFrame", type = CompositeFrame.class),
        @XmlElement(name = "CommonFrame")
    })
    protected List<Common_VersionFrameStructure> compositeFrameOrCommonFrame;

    /**
     * Gets the value of the compositeFrameOrCommonFrame property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compositeFrameOrCommonFrame property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompositeFrameOrCommonFrame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositeFrame }
     * {@link Common_VersionFrameStructure }
     * 
     * 
     */
    public List<Common_VersionFrameStructure> getCompositeFrameOrCommonFrame() {
        if (compositeFrameOrCommonFrame == null) {
            compositeFrameOrCommonFrame = new ArrayList<Common_VersionFrameStructure>();
        }
        return this.compositeFrameOrCommonFrame;
    }

}
