//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for DELIVERY VARIANT.
 * 
 * <p>Java class for DeliveryVariant_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryVariant_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}DataManagedObjectStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}DeliveryVariantGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryVariant_VersionStructure", propOrder = {
    "parentRef",
    "deliveryVariantMediaType",
    "typeOfDeliveryVariantRef",
    "variantText"
})
@XmlSeeAlso({
    DeliveryVariant.class
})
public class DeliveryVariant_VersionStructure
    extends DataManagedObjectStructure
{

    protected VersionOfObjectRefStructure parentRef;
    @XmlSchemaType(name = "normalizedString")
    protected DeliveryVariantTypeEnumeration deliveryVariantMediaType;
    protected TypeOfDeliveryVariantRefStructure typeOfDeliveryVariantRef;
    protected MultilingualStringEntity variantText;
    @XmlAttribute(name = "order")
    protected BigInteger order;

    /**
     * Gets the value of the parentRef property.
     * 
     * @return
     *     possible object is
     *     {@link VersionOfObjectRefStructure }
     *     
     */
    public VersionOfObjectRefStructure getParentRef() {
        return parentRef;
    }

    /**
     * Sets the value of the parentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionOfObjectRefStructure }
     *     
     */
    public void setParentRef(VersionOfObjectRefStructure value) {
        this.parentRef = value;
    }

    /**
     * Gets the value of the deliveryVariantMediaType property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryVariantTypeEnumeration }
     *     
     */
    public DeliveryVariantTypeEnumeration getDeliveryVariantMediaType() {
        return deliveryVariantMediaType;
    }

    /**
     * Sets the value of the deliveryVariantMediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryVariantTypeEnumeration }
     *     
     */
    public void setDeliveryVariantMediaType(DeliveryVariantTypeEnumeration value) {
        this.deliveryVariantMediaType = value;
    }

    /**
     * Gets the value of the typeOfDeliveryVariantRef property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfDeliveryVariantRefStructure }
     *     
     */
    public TypeOfDeliveryVariantRefStructure getTypeOfDeliveryVariantRef() {
        return typeOfDeliveryVariantRef;
    }

    /**
     * Sets the value of the typeOfDeliveryVariantRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfDeliveryVariantRefStructure }
     *     
     */
    public void setTypeOfDeliveryVariantRef(TypeOfDeliveryVariantRefStructure value) {
        this.typeOfDeliveryVariantRef = value;
    }

    /**
     * Gets the value of the variantText property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualStringEntity }
     *     
     */
    public MultilingualStringEntity getVariantText() {
        return variantText;
    }

    /**
     * Sets the value of the variantText property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualStringEntity }
     *     
     */
    public void setVariantText(MultilingualStringEntity value) {
        this.variantText = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

}
