//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a DEPARTMENT.
 * 
 * <p>Java class for Department_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Department_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}OrganisationPart_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}DepartmentGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Department_VersionStructure", propOrder = {
    "typeOfOperationRef",
    "units"
})
@XmlSeeAlso({
    Department.class,
    OperatingDepartment_VersionStructure.class
})
public class Department_VersionStructure
    extends OrganisationPart_VersionStructure
{

    protected TypeOfOperationRefStructure typeOfOperationRef;
    protected OrganisationalUnitRefs_RelStructure units;

    /**
     * Gets the value of the typeOfOperationRef property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfOperationRefStructure }
     *     
     */
    public TypeOfOperationRefStructure getTypeOfOperationRef() {
        return typeOfOperationRef;
    }

    /**
     * Sets the value of the typeOfOperationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfOperationRefStructure }
     *     
     */
    public void setTypeOfOperationRef(TypeOfOperationRefStructure value) {
        this.typeOfOperationRef = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationalUnitRefs_RelStructure }
     *     
     */
    public OrganisationalUnitRefs_RelStructure getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationalUnitRefs_RelStructure }
     *     
     */
    public void setUnits(OrganisationalUnitRefs_RelStructure value) {
        this.units = value;
    }

}
