//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntranceEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntranceEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="opening"/>
 *     &lt;enumeration value="openDoor"/>
 *     &lt;enumeration value="door"/>
 *     &lt;enumeration value="swingDoor"/>
 *     &lt;enumeration value="revolvingDoor"/>
 *     &lt;enumeration value="automaticDoor"/>
 *     &lt;enumeration value="ticketBarrier"/>
 *     &lt;enumeration value="gate"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntranceEnumeration")
public enum EntranceEnumeration {

    OPENING("opening"),
    OPEN_DOOR("openDoor"),
    DOOR("door"),
    SWING_DOOR("swingDoor"),
    REVOLVING_DOOR("revolvingDoor"),
    AUTOMATIC_DOOR("automaticDoor"),
    TICKET_BARRIER("ticketBarrier"),
    GATE("gate"),
    OTHER("other");
    private final String value;

    EntranceEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntranceEnumeration fromValue(String v) {
        for (EntranceEnumeration c: EntranceEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
