//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for MEETING RESTRICTION.
 * 
 * <p>Java class for MeetingRestriction_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeetingRestriction_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}InfrastructureLinkRestriction_VersionStructure">
 *       &lt;group ref="{http://www.netex.org.uk/netex}MeetingRestrictionGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeetingRestriction_VersionStructure", propOrder = {
    "forVehicleTypeRef",
    "againstVehicleTypeRef"
})
@XmlSeeAlso({
    MeetingRestriction.class
})
public class MeetingRestriction_VersionStructure
    extends InfrastructureLinkRestriction_VersionStructure
{

    protected VehicleTypeRefStructure forVehicleTypeRef;
    protected VehicleTypeRefStructure againstVehicleTypeRef;

    /**
     * Gets the value of the forVehicleTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleTypeRefStructure }
     *     
     */
    public VehicleTypeRefStructure getForVehicleTypeRef() {
        return forVehicleTypeRef;
    }

    /**
     * Sets the value of the forVehicleTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleTypeRefStructure }
     *     
     */
    public void setForVehicleTypeRef(VehicleTypeRefStructure value) {
        this.forVehicleTypeRef = value;
    }

    /**
     * Gets the value of the againstVehicleTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleTypeRefStructure }
     *     
     */
    public VehicleTypeRefStructure getAgainstVehicleTypeRef() {
        return againstVehicleTypeRef;
    }

    /**
     * Sets the value of the againstVehicleTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleTypeRefStructure }
     *     
     */
    public void setAgainstVehicleTypeRef(VehicleTypeRefStructure value) {
        this.againstVehicleTypeRef = value;
    }

}
