//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for NOTICE ASSIGNMENT.
 * 
 * <p>Java class for NoticeAssignment_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NoticeAssignment_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}Assignment_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}NoticeAssignmentGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoticeAssignment_VersionStructure", propOrder = {
    "noticeRef",
    "groupOfNoticesRef",
    "noticedObjectRef",
    "linkSequenceRef",
    "commonSectionRef",
    "startPointInPatternRef",
    "endPointInPatternRef",
    "mark",
    "markUrl",
    "publicityChannel",
    "advertised"
})
@XmlSeeAlso({
    NoticeAssignment.class
})
public class NoticeAssignment_VersionStructure
    extends Assignment_VersionStructure
{

    @XmlElement(name = "NoticeRef")
    protected NoticeRefStructure noticeRef;
    @XmlElement(name = "GroupOfNoticesRef")
    protected GeneralGroupOfEntitiesRefStructure groupOfNoticesRef;
    @XmlElement(name = "NoticedObjectRef")
    protected VersionOfObjectRefStructure noticedObjectRef;
    @XmlElementRef(name = "LinkSequenceRef", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends LinkSequenceRefStructure> linkSequenceRef;
    @XmlElementRef(name = "CommonSectionRef", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends CommonSectionRefStructure> commonSectionRef;
    @XmlElement(name = "StartPointInPatternRef")
    protected PointInSequenceRefStructure startPointInPatternRef;
    @XmlElement(name = "EndPointInPatternRef")
    protected PointInSequenceRefStructure endPointInPatternRef;
    @XmlElement(name = "Mark")
    protected String mark;
    @XmlElement(name = "MarkUrl")
    @XmlSchemaType(name = "anyURI")
    protected String markUrl;
    @XmlElement(name = "PublicityChannel", defaultValue = "all")
    @XmlSchemaType(name = "NMTOKEN")
    protected PublicityChannelEnumeration publicityChannel;
    @XmlElement(name = "Advertised")
    protected Boolean advertised;

    /**
     * Gets the value of the noticeRef property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeRefStructure }
     *     
     */
    public NoticeRefStructure getNoticeRef() {
        return noticeRef;
    }

    /**
     * Sets the value of the noticeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeRefStructure }
     *     
     */
    public void setNoticeRef(NoticeRefStructure value) {
        this.noticeRef = value;
    }

    /**
     * Gets the value of the groupOfNoticesRef property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralGroupOfEntitiesRefStructure }
     *     
     */
    public GeneralGroupOfEntitiesRefStructure getGroupOfNoticesRef() {
        return groupOfNoticesRef;
    }

    /**
     * Sets the value of the groupOfNoticesRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralGroupOfEntitiesRefStructure }
     *     
     */
    public void setGroupOfNoticesRef(GeneralGroupOfEntitiesRefStructure value) {
        this.groupOfNoticesRef = value;
    }

    /**
     * Gets the value of the noticedObjectRef property.
     * 
     * @return
     *     possible object is
     *     {@link VersionOfObjectRefStructure }
     *     
     */
    public VersionOfObjectRefStructure getNoticedObjectRef() {
        return noticedObjectRef;
    }

    /**
     * Sets the value of the noticedObjectRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionOfObjectRefStructure }
     *     
     */
    public void setNoticedObjectRef(VersionOfObjectRefStructure value) {
        this.noticedObjectRef = value;
    }

    /**
     * Gets the value of the linkSequenceRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeadRunJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link JourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServicePatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link LinkSequenceRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationPathRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TimingPatternRefStructure }{@code >}
     *     
     */
    public JAXBElement<? extends LinkSequenceRefStructure> getLinkSequenceRef() {
        return linkSequenceRef;
    }

    /**
     * Sets the value of the linkSequenceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeadRunJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link JourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServicePatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link LinkSequenceRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationPathRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TimingPatternRefStructure }{@code >}
     *     
     */
    public void setLinkSequenceRef(JAXBElement<? extends LinkSequenceRefStructure> value) {
        this.linkSequenceRef = value;
    }

    /**
     * Gets the value of the commonSectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CommonSectionRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link FareSectionRefStructure }{@code >}
     *     
     */
    public JAXBElement<? extends CommonSectionRefStructure> getCommonSectionRef() {
        return commonSectionRef;
    }

    /**
     * Sets the value of the commonSectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CommonSectionRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link FareSectionRefStructure }{@code >}
     *     
     */
    public void setCommonSectionRef(JAXBElement<? extends CommonSectionRefStructure> value) {
        this.commonSectionRef = value;
    }

    /**
     * Gets the value of the startPointInPatternRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointInSequenceRefStructure }
     *     
     */
    public PointInSequenceRefStructure getStartPointInPatternRef() {
        return startPointInPatternRef;
    }

    /**
     * Sets the value of the startPointInPatternRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInSequenceRefStructure }
     *     
     */
    public void setStartPointInPatternRef(PointInSequenceRefStructure value) {
        this.startPointInPatternRef = value;
    }

    /**
     * Gets the value of the endPointInPatternRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointInSequenceRefStructure }
     *     
     */
    public PointInSequenceRefStructure getEndPointInPatternRef() {
        return endPointInPatternRef;
    }

    /**
     * Sets the value of the endPointInPatternRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInSequenceRefStructure }
     *     
     */
    public void setEndPointInPatternRef(PointInSequenceRefStructure value) {
        this.endPointInPatternRef = value;
    }

    /**
     * Gets the value of the mark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMark(String value) {
        this.mark = value;
    }

    /**
     * Gets the value of the markUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkUrl() {
        return markUrl;
    }

    /**
     * Sets the value of the markUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkUrl(String value) {
        this.markUrl = value;
    }

    /**
     * Gets the value of the publicityChannel property.
     * 
     * @return
     *     possible object is
     *     {@link PublicityChannelEnumeration }
     *     
     */
    public PublicityChannelEnumeration getPublicityChannel() {
        return publicityChannel;
    }

    /**
     * Sets the value of the publicityChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicityChannelEnumeration }
     *     
     */
    public void setPublicityChannel(PublicityChannelEnumeration value) {
        this.publicityChannel = value;
    }

    /**
     * Gets the value of the advertised property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdvertised() {
        return advertised;
    }

    /**
     * Sets the value of the advertised property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdvertised(Boolean value) {
        this.advertised = value;
    }

}
