//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a POINT PROJECTION.
 * 
 * <p>Java class for PointProjection_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointProjection_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}Projection_VersionStructure">
 *       &lt;sequence>
 *         &lt;element name="ProjectedPointRef" type="{http://www.netex.org.uk/netex}PointRefStructure" minOccurs="0"/>
 *         &lt;element name="ProjectToPointRef" type="{http://www.netex.org.uk/netex}PointRefStructure" minOccurs="0"/>
 *         &lt;element name="ProjectToLinkRef" type="{http://www.netex.org.uk/netex}LinkRefStructure" minOccurs="0"/>
 *         &lt;element name="Distance" type="{http://www.netex.org.uk/netex}LengthType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointProjection_VersionStructure", propOrder = {
    "projectedPointRef",
    "projectToPointRef",
    "projectToLinkRef",
    "distance"
})
@XmlSeeAlso({
    PointProjection.class
})
public class PointProjection_VersionStructure
    extends Projection_VersionStructure
{

    @XmlElement(name = "ProjectedPointRef")
    protected PointRefStructure projectedPointRef;
    @XmlElement(name = "ProjectToPointRef")
    protected PointRefStructure projectToPointRef;
    @XmlElement(name = "ProjectToLinkRef")
    protected LinkRefStructure projectToLinkRef;
    @XmlElement(name = "Distance")
    protected BigDecimal distance;

    /**
     * Gets the value of the projectedPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointRefStructure }
     *     
     */
    public PointRefStructure getProjectedPointRef() {
        return projectedPointRef;
    }

    /**
     * Sets the value of the projectedPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointRefStructure }
     *     
     */
    public void setProjectedPointRef(PointRefStructure value) {
        this.projectedPointRef = value;
    }

    /**
     * Gets the value of the projectToPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointRefStructure }
     *     
     */
    public PointRefStructure getProjectToPointRef() {
        return projectToPointRef;
    }

    /**
     * Sets the value of the projectToPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointRefStructure }
     *     
     */
    public void setProjectToPointRef(PointRefStructure value) {
        this.projectToPointRef = value;
    }

    /**
     * Gets the value of the projectToLinkRef property.
     * 
     * @return
     *     possible object is
     *     {@link LinkRefStructure }
     *     
     */
    public LinkRefStructure getProjectToLinkRef() {
        return projectToLinkRef;
    }

    /**
     * Sets the value of the projectToLinkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkRefStructure }
     *     
     */
    public void setProjectToLinkRef(LinkRefStructure value) {
        this.projectToLinkRef = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistance(BigDecimal value) {
        this.distance = value;
    }

}
