//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for a POINT.
 * 
 * <p>Java class for Point_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Point_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}DataManagedObjectStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}PointGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Point_VersionStructure", propOrder = {
    "name",
    "location",
    "pointNumber",
    "types",
    "projections",
    "groupMemberships"
})
@XmlSeeAlso({
    RoutePoint_VersionStructure.class,
    PathJunction_VersionStructure.class,
    ActivationPoint_VersionStructure.class,
    InfrastructurePoint_VersionStructure.class,
    TrafficControlPoint_VersionStructure.class,
    TimingPoint_VersionStructure.class
})
public class Point_VersionStructure
    extends DataManagedObjectStructure
{

    @XmlElement(name = "Name")
    protected MultilingualString name;
    @XmlElement(name = "Location")
    protected LocationStructure location;
    @XmlElement(name = "PointNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String pointNumber;
    protected TypeOfPointRefs_RelStructure types;
    protected Projections_RelStructure projections;
    protected GroupMembershipRefs_RelStructure groupMemberships;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setName(MultilingualString value) {
        this.name = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setLocation(LocationStructure value) {
        this.location = value;
    }

    /**
     * Gets the value of the pointNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointNumber() {
        return pointNumber;
    }

    /**
     * Sets the value of the pointNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointNumber(String value) {
        this.pointNumber = value;
    }

    /**
     * Gets the value of the types property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfPointRefs_RelStructure }
     *     
     */
    public TypeOfPointRefs_RelStructure getTypes() {
        return types;
    }

    /**
     * Sets the value of the types property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfPointRefs_RelStructure }
     *     
     */
    public void setTypes(TypeOfPointRefs_RelStructure value) {
        this.types = value;
    }

    /**
     * Gets the value of the projections property.
     * 
     * @return
     *     possible object is
     *     {@link Projections_RelStructure }
     *     
     */
    public Projections_RelStructure getProjections() {
        return projections;
    }

    /**
     * Sets the value of the projections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Projections_RelStructure }
     *     
     */
    public void setProjections(Projections_RelStructure value) {
        this.projections = value;
    }

    /**
     * Gets the value of the groupMemberships property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMembershipRefs_RelStructure }
     *     
     */
    public GroupMembershipRefs_RelStructure getGroupMemberships() {
        return groupMemberships;
    }

    /**
     * Sets the value of the groupMemberships property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMembershipRefs_RelStructure }
     *     
     */
    public void setGroupMemberships(GroupMembershipRefs_RelStructure value) {
        this.groupMemberships = value;
    }

}
