//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelativeOperatorEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelativeOperatorEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="NE"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GT"/>
 *     &lt;enumeration value="LE"/>
 *     &lt;enumeration value="LT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RelativeOperatorEnumeration")
public enum RelativeOperatorEnumeration {


    /**
     * This is a definition of a new entity.
     * 
     */
    EQ,
    NE,
    GE,

    /**
     * This is a deletion of an existing entity.
     * 
     */
    GT,
    LE,

    /**
     * This is a revision to an existing entity. All values are replaced.
     * 
     */
    LT;

    public String value() {
        return name();
    }

    public static RelativeOperatorEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
