//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for RELIEF POINT.
 * 
 * <p>Java class for ReliefPoint_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReliefPoint_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}TimingPoint_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}ReliefPointGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReliefPoint_VersionStructure", propOrder = {
    "crewBaseRef"
})
@XmlSeeAlso({
    ReliefPoint.class,
    ParkingPoint_VersionStructure.class
})
public class ReliefPoint_VersionStructure
    extends TimingPoint_VersionStructure
{

    @XmlElement(name = "CrewBaseRef")
    protected CrewBaseRefStructure crewBaseRef;

    /**
     * Gets the value of the crewBaseRef property.
     * 
     * @return
     *     possible object is
     *     {@link CrewBaseRefStructure }
     *     
     */
    public CrewBaseRefStructure getCrewBaseRef() {
        return crewBaseRef;
    }

    /**
     * Sets the value of the crewBaseRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrewBaseRefStructure }
     *     
     */
    public void setCrewBaseRef(CrewBaseRefStructure value) {
        this.crewBaseRef = value;
    }

}
