//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a list of SCHEMATIC MAP.
 * 
 * <p>Java class for schematicMapMembers_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schematicMapMembers_RelStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}strictContainmentAggregationStructure">
 *       &lt;sequence>
 *         &lt;element name="SchematicMapMember" type="{http://www.netex.org.uk/netex}SchematicMapMember_VersionedChildStructure" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schematicMapMembers_RelStructure", propOrder = {
    "schematicMapMember"
})
public class SchematicMapMembers_RelStructure
    extends StrictContainmentAggregationStructure
{

    protected List<SchematicMapMember_VersionedChildStructure> schematicMapMember;

    /**
     * Gets the value of the schematicMapMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schematicMapMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchematicMapMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchematicMapMember_VersionedChildStructure }
     * 
     * 
     */
    public List<SchematicMapMember_VersionedChildStructure> getSchematicMapMember() {
        if (schematicMapMember == null) {
            schematicMapMember = new ArrayList<SchematicMapMember_VersionedChildStructure>();
        }
        return this.schematicMapMember;
    }

}
