//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SectionTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SectionTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="trunk"/>
 *     &lt;enumeration value="branch"/>
 *     &lt;enumeration value="endLoop"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SectionTypeEnumeration")
@XmlEnum
public enum SectionTypeEnumeration {

    @XmlEnumValue("trunk")
    TRUNK("trunk"),
    @XmlEnumValue("branch")
    BRANCH("branch"),
    @XmlEnumValue("endLoop")
    END_LOOP("endLoop"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    SectionTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SectionTypeEnumeration fromValue(String v) {
        for (SectionTypeEnumeration c: SectionTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
