//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package org.rutebanken.tiamat.model;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a TRAIN STOP POINT ASSIGNMENT.
 * 
 * <p>Java class for TrainStopAssignment_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainStopAssignment_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}StopAssignment_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}TrainStopAssignmentGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainStopAssignment_VersionStructure", propOrder = {
    "passengerStopAssignmentRef",
    "trainRef",
    "trainComponentRef",
    "trainComponentView",
    "positionOfTrainElement",
    "boardingPositionRef",
    "entranceToVehicle"
})
@XmlSeeAlso({
    TrainStopAssignment.class
})
public class TrainStopAssignment_VersionStructure
    extends StopAssignment_VersionStructure
{

    @XmlElementRef(name = "PassengerStopAssignmentRef", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends PassengerStopAssignmentRefStructure> passengerStopAssignmentRef;
    @XmlElement(name = "TrainRef")
    protected TrainRefStructure trainRef;
    @XmlElement(name = "TrainComponentRef")
    protected TrainComponentRefStructure trainComponentRef;
    @XmlElement(name = "TrainComponentView")
    protected TrainComponentView trainComponentView;
    @XmlElement(name = "PositionOfTrainElement")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger positionOfTrainElement;
    @XmlElement(name = "BoardingPositionRef")
    protected BoardingPositionRefStructure boardingPositionRef;
    @XmlElement(name = "EntranceToVehicle")
    protected MultilingualStringEntity entranceToVehicle;

    /**
     * Gets the value of the passengerStopAssignmentRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DynamicStopAssignmentRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerStopAssignmentRefStructure }{@code >}
     *     
     */
    public JAXBElement<? extends PassengerStopAssignmentRefStructure> getPassengerStopAssignmentRef() {
        return passengerStopAssignmentRef;
    }

    /**
     * Sets the value of the passengerStopAssignmentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DynamicStopAssignmentRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerStopAssignmentRefStructure }{@code >}
     *     
     */
    public void setPassengerStopAssignmentRef(JAXBElement<? extends PassengerStopAssignmentRefStructure> value) {
        this.passengerStopAssignmentRef = value;
    }

    /**
     * Gets the value of the trainRef property.
     * 
     * @return
     *     possible object is
     *     {@link TrainRefStructure }
     *     
     */
    public TrainRefStructure getTrainRef() {
        return trainRef;
    }

    /**
     * Sets the value of the trainRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainRefStructure }
     *     
     */
    public void setTrainRef(TrainRefStructure value) {
        this.trainRef = value;
    }

    /**
     * Gets the value of the trainComponentRef property.
     * 
     * @return
     *     possible object is
     *     {@link TrainComponentRefStructure }
     *     
     */
    public TrainComponentRefStructure getTrainComponentRef() {
        return trainComponentRef;
    }

    /**
     * Sets the value of the trainComponentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainComponentRefStructure }
     *     
     */
    public void setTrainComponentRef(TrainComponentRefStructure value) {
        this.trainComponentRef = value;
    }

    /**
     * Gets the value of the trainComponentView property.
     * 
     * @return
     *     possible object is
     *     {@link TrainComponentView }
     *     
     */
    public TrainComponentView getTrainComponentView() {
        return trainComponentView;
    }

    /**
     * Sets the value of the trainComponentView property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainComponentView }
     *     
     */
    public void setTrainComponentView(TrainComponentView value) {
        this.trainComponentView = value;
    }

    /**
     * Gets the value of the positionOfTrainElement property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionOfTrainElement() {
        return positionOfTrainElement;
    }

    /**
     * Sets the value of the positionOfTrainElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionOfTrainElement(BigInteger value) {
        this.positionOfTrainElement = value;
    }

    /**
     * Gets the value of the boardingPositionRef property.
     * 
     * @return
     *     possible object is
     *     {@link BoardingPositionRefStructure }
     *     
     */
    public BoardingPositionRefStructure getBoardingPositionRef() {
        return boardingPositionRef;
    }

    /**
     * Sets the value of the boardingPositionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardingPositionRefStructure }
     *     
     */
    public void setBoardingPositionRef(BoardingPositionRefStructure value) {
        this.boardingPositionRef = value;
    }

    /**
     * Gets the value of the entranceToVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualStringEntity }
     *     
     */
    public MultilingualStringEntity getEntranceToVehicle() {
        return entranceToVehicle;
    }

    /**
     * Sets the value of the entranceToVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualStringEntity }
     *     
     */
    public void setEntranceToVehicle(MultilingualStringEntity value) {
        this.entranceToVehicle = value;
    }

}
