env: tst
gcp2:
  enabled: true
sql:
  instance: ent-tiamat-tst:europe-west1:tiamat-db-1=tcp:5432

envVars:
  BLOBSTORE_GCS_BUCKET_NAME: ror-tiamat-gcp2-tst
  BLOBSTORE_GCS_PROJECT_ID: ent-tiamat-tst
  SPRING_CLOUD_GCP_PROJECT_ID: ent-tiamat-tst
  FAREZONE_EXTERNALVERSIONING: "true"
  TIAMAT_USER_PERMISSION_REST_SERVICE_URL: http://baba.tst.entur.internal/services/organisations/users
  TIAMAT_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_ISSUER_URI: https://partner.staging.entur.org/
  TIAMAT_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_AUDIENCE: https://api.staging.entur.io
  TIAMAT_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_INTERNAL_JWT_ISSUER_URI: https://internal.staging.entur.org/
  TIAMAT_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_INTERNAL_JWT_AUDIENCE: https://api.staging.entur.io
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_INTERNAL_TOKEN_URI: https://internal.staging.entur.org/oauth/token
  TIAMAT_OAUTH2_CLIENT_AUDIENCE: https://api.staging.entur.io

rbac:
  enabled: true

ingress:
  enabled: true
  domainName: .staging.entur.io
