gcp_project = "entur-dev-1287"
cloudsql_project = "entur-ror-dev"
pubsub_project = "entur-ror-dev"
storage_project = "entur-ror-dev"
kube_namespace = "dev"
bucket_instance_suffix = "dev"
location = "europe-west1"
service_account_bucket_role = "roles/storage.objectCreator"
