gcp_project = "neon-1287"
cloudsql_project = "neon-1287"
pubsub_project = "entur-ror-prod"
storage_project = "neon-1287"
kube_namespace = "production"
bucket_instance_suffix = "production"
location = "europe-west1"
service_account_bucket_role = "roles/storage.objectCreator"