gcp_project = "entur-test-1287"
cloudsql_project = "entur-ror-test"
pubsub_project = "entur-ror-test"
storage_project = "entur-ror-test"
kube_namespace = "staging"
bucket_instance_suffix ="test"
location = "europe-west1"
service_account_bucket_role = "roles/storage.objectCreator"