//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a User Member of COMMON SECTION.
 * 
 * <p>Java class for CommonSectionSequenceMemberStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonSectionSequenceMemberStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}AbstractGroupMember_VersionedChildStructure">
 *       &lt;sequence>
 *         &lt;element name="ParentCommonSectionRef" type="{http://www.netex.org.uk/netex}CommonSectionRefStructure" minOccurs="0"/>
 *         &lt;element ref="{http://www.netex.org.uk/netex}LinkSequenceRef"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonSectionSequenceMemberStructure", propOrder = {
    "parentCommonSectionRef",
    "linkSequenceRef"
})
public class CommonSectionSequenceMemberStructure
    extends AbstractGroupMember_VersionedChildStructure
{

    @XmlElement(name = "ParentCommonSectionRef")
    protected CommonSectionRefStructure parentCommonSectionRef;
    @XmlElementRef(name = "LinkSequenceRef", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class)
    protected JAXBElement<? extends LinkSequenceRefStructure> linkSequenceRef;

    /**
     * Gets the value of the parentCommonSectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link CommonSectionRefStructure }
     *     
     */
    public CommonSectionRefStructure getParentCommonSectionRef() {
        return parentCommonSectionRef;
    }

    /**
     * Sets the value of the parentCommonSectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonSectionRefStructure }
     *     
     */
    public void setParentCommonSectionRef(CommonSectionRefStructure value) {
        this.parentCommonSectionRef = value;
    }

    /**
     * Reference to a LINK SEQUENCE.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeadRunJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link JourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServicePatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link LinkSequenceRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationPathRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TimingPatternRefStructure }{@code >}
     *     
     */
    public JAXBElement<? extends LinkSequenceRefStructure> getLinkSequenceRef() {
        return linkSequenceRef;
    }

    /**
     * Sets the value of the linkSequenceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeadRunJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceJourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link JourneyPatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServicePatternRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link LinkSequenceRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationPathRefStructure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TimingPatternRefStructure }{@code >}
     *     
     */
    public void setLinkSequenceRef(JAXBElement<? extends LinkSequenceRefStructure> value) {
        this.linkSequenceRef = value;
    }

}
