//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a GROUP OF TIMEBANDS.
 * 
 * <p>Java class for GroupOfTimebands_VersionedChildStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupOfTimebands_VersionedChildStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}GroupOfEntities_VersionStructure">
 *       &lt;group ref="{http://www.netex.org.uk/netex}GroupOfTimebandsGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupOfTimebands_VersionedChildStructure", propOrder = {
    "timebands"
})
@XmlSeeAlso({
    GroupOfTimebands.class
})
public class GroupOfTimebands_VersionedChildStructure
    extends GroupOfEntities_VersionStructure
{

    protected TimebandRefs_RelStructure timebands;

    /**
     * Gets the value of the timebands property.
     * 
     * @return
     *     possible object is
     *     {@link TimebandRefs_RelStructure }
     *     
     */
    public TimebandRefs_RelStructure getTimebands() {
        return timebands;
    }

    /**
     * Sets the value of the timebands property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimebandRefs_RelStructure }
     *     
     */
    public void setTimebands(TimebandRefs_RelStructure value) {
        this.timebands = value;
    }

}
