//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HolidayTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HolidayTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AnyDay"/>
 *     &lt;enumeration value="WorkingDay"/>
 *     &lt;enumeration value="SchoolDay"/>
 *     &lt;enumeration value="NotHoliday"/>
 *     &lt;enumeration value="NotWorkingDay"/>
 *     &lt;enumeration value="NotSchoolDay"/>
 *     &lt;enumeration value="AnyHoliday"/>
 *     &lt;enumeration value="LocalHoliday"/>
 *     &lt;enumeration value="RegionalHoliday"/>
 *     &lt;enumeration value="NationalHoliday"/>
 *     &lt;enumeration value="HolidayDisplacementDay"/>
 *     &lt;enumeration value="EveOfHoliday"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HolidayTypeEnumeration")
@XmlEnum
public enum HolidayTypeEnumeration {

    @XmlEnumValue("AnyDay")
    ANY_DAY("AnyDay"),
    @XmlEnumValue("WorkingDay")
    WORKING_DAY("WorkingDay"),
    @XmlEnumValue("SchoolDay")
    SCHOOL_DAY("SchoolDay"),
    @XmlEnumValue("NotHoliday")
    NOT_HOLIDAY("NotHoliday"),
    @XmlEnumValue("NotWorkingDay")
    NOT_WORKING_DAY("NotWorkingDay"),
    @XmlEnumValue("NotSchoolDay")
    NOT_SCHOOL_DAY("NotSchoolDay"),
    @XmlEnumValue("AnyHoliday")
    ANY_HOLIDAY("AnyHoliday"),
    @XmlEnumValue("LocalHoliday")
    LOCAL_HOLIDAY("LocalHoliday"),
    @XmlEnumValue("RegionalHoliday")
    REGIONAL_HOLIDAY("RegionalHoliday"),
    @XmlEnumValue("NationalHoliday")
    NATIONAL_HOLIDAY("NationalHoliday"),
    @XmlEnumValue("HolidayDisplacementDay")
    HOLIDAY_DISPLACEMENT_DAY("HolidayDisplacementDay"),
    @XmlEnumValue("EveOfHoliday")
    EVE_OF_HOLIDAY("EveOfHoliday");
    private final String value;

    HolidayTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HolidayTypeEnumeration fromValue(String v) {
        for (HolidayTypeEnumeration c: HolidayTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
