//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}IfoptPayloadGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organisations",
    "responsibilitySets",
    "sites",
    "stopAssignments",
    "connections",
    "navigationPaths",
    "schematicMaps"
})
@XmlRootElement(name = "IFOPT")
public class IFOPT {

    protected IFOPT.Organisations organisations;
    protected IFOPT.ResponsibilitySets responsibilitySets;
    protected IFOPT.Sites sites;
    protected IFOPT.StopAssignments stopAssignments;
    protected IFOPT.Connections connections;
    protected IFOPT.NavigationPaths navigationPaths;
    protected IFOPT.SchematicMaps schematicMaps;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String version;

    /**
     * Gets the value of the organisations property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.Organisations }
     *     
     */
    public IFOPT.Organisations getOrganisations() {
        return organisations;
    }

    /**
     * Sets the value of the organisations property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.Organisations }
     *     
     */
    public void setOrganisations(IFOPT.Organisations value) {
        this.organisations = value;
    }

    /**
     * Gets the value of the responsibilitySets property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.ResponsibilitySets }
     *     
     */
    public IFOPT.ResponsibilitySets getResponsibilitySets() {
        return responsibilitySets;
    }

    /**
     * Sets the value of the responsibilitySets property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.ResponsibilitySets }
     *     
     */
    public void setResponsibilitySets(IFOPT.ResponsibilitySets value) {
        this.responsibilitySets = value;
    }

    /**
     * Gets the value of the sites property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.Sites }
     *     
     */
    public IFOPT.Sites getSites() {
        return sites;
    }

    /**
     * Sets the value of the sites property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.Sites }
     *     
     */
    public void setSites(IFOPT.Sites value) {
        this.sites = value;
    }

    /**
     * Gets the value of the stopAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.StopAssignments }
     *     
     */
    public IFOPT.StopAssignments getStopAssignments() {
        return stopAssignments;
    }

    /**
     * Sets the value of the stopAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.StopAssignments }
     *     
     */
    public void setStopAssignments(IFOPT.StopAssignments value) {
        this.stopAssignments = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.Connections }
     *     
     */
    public IFOPT.Connections getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.Connections }
     *     
     */
    public void setConnections(IFOPT.Connections value) {
        this.connections = value;
    }

    /**
     * Gets the value of the navigationPaths property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.NavigationPaths }
     *     
     */
    public IFOPT.NavigationPaths getNavigationPaths() {
        return navigationPaths;
    }

    /**
     * Sets the value of the navigationPaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.NavigationPaths }
     *     
     */
    public void setNavigationPaths(IFOPT.NavigationPaths value) {
        this.navigationPaths = value;
    }

    /**
     * Gets the value of the schematicMaps property.
     * 
     * @return
     *     possible object is
     *     {@link IFOPT.SchematicMaps }
     *     
     */
    public IFOPT.SchematicMaps getSchematicMaps() {
        return schematicMaps;
    }

    /**
     * Sets the value of the schematicMaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFOPT.SchematicMaps }
     *     
     */
    public void setSchematicMaps(IFOPT.SchematicMaps value) {
        this.schematicMaps = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.netex.org.uk/netex}Access" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.netex.org.uk/netex}Connection" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.netex.org.uk/netex}DefaultConnection" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.netex.org.uk/netex}SiteConnection" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "access",
        "connection",
        "defaultConnection",
        "siteConnection"
    })
    public static class Connections {

        @XmlElement(name = "Access")
        protected List<Access> access;
        @XmlElement(name = "Connection")
        protected List<Connection> connection;
        @XmlElement(name = "DefaultConnection")
        protected List<DefaultConnection> defaultConnection;
        @XmlElement(name = "SiteConnection")
        protected List<SiteConnection> siteConnection;

        /**
         * Gets the value of the access property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the access property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccess().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Access }
         * 
         * 
         */
        public List<Access> getAccess() {
            if (access == null) {
                access = new ArrayList<Access>();
            }
            return this.access;
        }

        /**
         * Gets the value of the connection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the connection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Connection }
         * 
         * 
         */
        public List<Connection> getConnection() {
            if (connection == null) {
                connection = new ArrayList<Connection>();
            }
            return this.connection;
        }

        /**
         * Gets the value of the defaultConnection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the defaultConnection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDefaultConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DefaultConnection }
         * 
         * 
         */
        public List<DefaultConnection> getDefaultConnection() {
            if (defaultConnection == null) {
                defaultConnection = new ArrayList<DefaultConnection>();
            }
            return this.defaultConnection;
        }

        /**
         * Gets the value of the siteConnection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the siteConnection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSiteConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SiteConnection }
         * 
         * 
         */
        public List<SiteConnection> getSiteConnection() {
            if (siteConnection == null) {
                siteConnection = new ArrayList<SiteConnection>();
            }
            return this.siteConnection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.netex.org.uk/netex}NavigationPath" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "navigationPath"
    })
    public static class NavigationPaths {

        @XmlElement(name = "NavigationPath", required = true)
        protected List<NavigationPath> navigationPath;

        /**
         * Gets the value of the navigationPath property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the navigationPath property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNavigationPath().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NavigationPath }
         * 
         * 
         */
        public List<NavigationPath> getNavigationPath() {
            if (navigationPath == null) {
                navigationPath = new ArrayList<NavigationPath>();
            }
            return this.navigationPath;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element ref="{http://www.netex.org.uk/netex}Organisation_" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organisation_"
    })
    public static class Organisations {

        @XmlElementRef(name = "Organisation_", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false)
        protected List<JAXBElement<? extends DataManagedObjectStructure>> organisation_;

        /**
         * Gets the value of the organisation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the organisation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrganisation_().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Authority }{@code >}
         * {@link JAXBElement }{@code <}{@link OtherOrganisation }{@code >}
         * {@link JAXBElement }{@code <}{@link TravelAgent }{@code >}
         * {@link JAXBElement }{@code <}{@link Organisation }{@code >}
         * {@link JAXBElement }{@code <}{@link GeneralOrganisation }{@code >}
         * {@link JAXBElement }{@code <}{@link Organisation_VersionStructure }{@code >}
         * {@link JAXBElement }{@code <}{@link ManagementAgent }{@code >}
         * {@link JAXBElement }{@code <}{@link ServicedOrganisation }{@code >}
         * {@link JAXBElement }{@code <}{@link DataManagedObjectStructure }{@code >}
         * {@link JAXBElement }{@code <}{@link Operator }{@code >}
         * 
         * 
         */
        public List<JAXBElement<? extends DataManagedObjectStructure>> getOrganisation_() {
            if (organisation_ == null) {
                organisation_ = new ArrayList<JAXBElement<? extends DataManagedObjectStructure>>();
            }
            return this.organisation_;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.netex.org.uk/netex}ResponsibilitySet" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responsibilitySet"
    })
    public static class ResponsibilitySets {

        @XmlElement(name = "ResponsibilitySet", required = true)
        protected List<ResponsibilitySet> responsibilitySet;

        /**
         * Gets the value of the responsibilitySet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsibilitySet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsibilitySet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResponsibilitySet }
         * 
         * 
         */
        public List<ResponsibilitySet> getResponsibilitySet() {
            if (responsibilitySet == null) {
                responsibilitySet = new ArrayList<ResponsibilitySet>();
            }
            return this.responsibilitySet;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.netex.org.uk/netex}SchematicMap" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schematicMap"
    })
    public static class SchematicMaps {

        @XmlElement(name = "SchematicMap")
        protected SchematicMap schematicMap;

        /**
         * Gets the value of the schematicMap property.
         * 
         * @return
         *     possible object is
         *     {@link SchematicMap }
         *     
         */
        public SchematicMap getSchematicMap() {
            return schematicMap;
        }

        /**
         * Sets the value of the schematicMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchematicMap }
         *     
         */
        public void setSchematicMap(SchematicMap value) {
            this.schematicMap = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stopPlaces" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.netex.org.uk/netex}StopPlace" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="pointsOfInterest" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.netex.org.uk/netex}PointOfInterest" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="parkings" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.netex.org.uk/netex}Parking" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stopPlaces",
        "pointsOfInterest",
        "parkings"
    })
    public static class Sites {

        protected IFOPT.Sites.StopPlaces stopPlaces;
        protected IFOPT.Sites.PointsOfInterest pointsOfInterest;
        protected IFOPT.Sites.Parkings parkings;

        /**
         * Gets the value of the stopPlaces property.
         * 
         * @return
         *     possible object is
         *     {@link IFOPT.Sites.StopPlaces }
         *     
         */
        public IFOPT.Sites.StopPlaces getStopPlaces() {
            return stopPlaces;
        }

        /**
         * Sets the value of the stopPlaces property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFOPT.Sites.StopPlaces }
         *     
         */
        public void setStopPlaces(IFOPT.Sites.StopPlaces value) {
            this.stopPlaces = value;
        }

        /**
         * Gets the value of the pointsOfInterest property.
         * 
         * @return
         *     possible object is
         *     {@link IFOPT.Sites.PointsOfInterest }
         *     
         */
        public IFOPT.Sites.PointsOfInterest getPointsOfInterest() {
            return pointsOfInterest;
        }

        /**
         * Sets the value of the pointsOfInterest property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFOPT.Sites.PointsOfInterest }
         *     
         */
        public void setPointsOfInterest(IFOPT.Sites.PointsOfInterest value) {
            this.pointsOfInterest = value;
        }

        /**
         * Gets the value of the parkings property.
         * 
         * @return
         *     possible object is
         *     {@link IFOPT.Sites.Parkings }
         *     
         */
        public IFOPT.Sites.Parkings getParkings() {
            return parkings;
        }

        /**
         * Sets the value of the parkings property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFOPT.Sites.Parkings }
         *     
         */
        public void setParkings(IFOPT.Sites.Parkings value) {
            this.parkings = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.netex.org.uk/netex}Parking" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parking"
        })
        public static class Parkings {

            @XmlElement(name = "Parking")
            protected List<Parking> parking;

            /**
             * Gets the value of the parking property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parking property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParking().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parking }
             * 
             * 
             */
            public List<Parking> getParking() {
                if (parking == null) {
                    parking = new ArrayList<Parking>();
                }
                return this.parking;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.netex.org.uk/netex}PointOfInterest" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pointOfInterest"
        })
        public static class PointsOfInterest {

            @XmlElement(name = "PointOfInterest")
            protected List<PointOfInterest> pointOfInterest;

            /**
             * Gets the value of the pointOfInterest property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pointOfInterest property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPointOfInterest().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PointOfInterest }
             * 
             * 
             */
            public List<PointOfInterest> getPointOfInterest() {
                if (pointOfInterest == null) {
                    pointOfInterest = new ArrayList<PointOfInterest>();
                }
                return this.pointOfInterest;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.netex.org.uk/netex}StopPlace" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stopPlace"
        })
        public static class StopPlaces {

            @XmlElement(name = "StopPlace")
            protected List<StopPlace> stopPlace;

            /**
             * Gets the value of the stopPlace property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stopPlace property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStopPlace().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link StopPlace }
             * 
             * 
             */
            public List<StopPlace> getStopPlace() {
                if (stopPlace == null) {
                    stopPlace = new ArrayList<StopPlace>();
                }
                return this.stopPlace;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.netex.org.uk/netex}PassengerStopAssignment" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passengerStopAssignment"
    })
    public static class StopAssignments {

        @XmlElement(name = "PassengerStopAssignment", required = true)
        protected List<PassengerStopAssignment> passengerStopAssignment;

        /**
         * Gets the value of the passengerStopAssignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerStopAssignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerStopAssignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassengerStopAssignment }
         * 
         * 
         */
        public List<PassengerStopAssignment> getPassengerStopAssignment() {
            if (passengerStopAssignment == null) {
                passengerStopAssignment = new ArrayList<PassengerStopAssignment>();
            }
            return this.passengerStopAssignment;
        }

    }

}
