//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for NAVIGATION PATH.
 * 
 * <p>Java class for NavigationPath_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NavigationPath_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}LinkSequence_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}NavigationPathSummaryGroup"/>
 *         &lt;group ref="{http://www.netex.org.uk/netex}SiteElementPropertiesGroup"/>
 *         &lt;group ref="{http://www.netex.org.uk/netex}NavigationPathGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavigationPath_VersionStructure", propOrder = {
    "from",
    "to",
    "accessibilityAssessment",
    "accessModes",
    "summaries",
    "transferDuration",
    "publicUse",
    "covered",
    "gated",
    "lighting",
    "allAreasWheelchairAccessible",
    "personCapacity",
    "facilities",
    "accessFeatureList",
    "navigationType",
    "placesInSequence",
    "pathLinksInSequence",
    "transfers"
})
@XmlSeeAlso({
    NavigationPath.class
})
public class NavigationPath_VersionStructure
    extends LinkSequence_VersionStructure
{

    @XmlElement(name = "From")
    protected PathLinkEndStructure from;
    @XmlElement(name = "To")
    protected PathLinkEndStructure to;
    @XmlElement(name = "AccessibilityAssessment")
    protected AccessibilityAssessment accessibilityAssessment;
    @XmlList
    @XmlElement(name = "AccessModes")
    @XmlSchemaType(name = "anySimpleType")
    protected List<AccessModeEnumeration> accessModes;
    protected AccessSummaries_RelStructure summaries;
    @XmlElement(name = "TransferDuration")
    protected TransferDurationStructure transferDuration;
    @XmlElement(name = "PublicUse", defaultValue = "all")
    @XmlSchemaType(name = "string")
    protected PublicUseEnumeration publicUse;
    @XmlElement(name = "Covered", defaultValue = "indoors")
    @XmlSchemaType(name = "string")
    protected CoveredEnumeration covered;
    @XmlElement(name = "Gated")
    @XmlSchemaType(name = "string")
    protected GatedEnumeration gated;
    @XmlElement(name = "Lighting", defaultValue = "wellLit")
    @XmlSchemaType(name = "normalizedString")
    protected LightingEnumeration lighting;
    @XmlElement(name = "AllAreasWheelchairAccessible", defaultValue = "true")
    protected Boolean allAreasWheelchairAccessible;
    @XmlElement(name = "PersonCapacity")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger personCapacity;
    protected SiteFacilitySets_RelStructure facilities;
    @XmlList
    @XmlElement(name = "AccessFeatureList")
    @XmlSchemaType(name = "anySimpleType")
    protected List<AccessFeatureEnumeration> accessFeatureList;
    @XmlElement(name = "NavigationType")
    @XmlSchemaType(name = "NMTOKEN")
    protected NavigationTypeEnumeration navigationType;
    protected PlacesInSequence_RelStructure placesInSequence;
    protected PathLinksInSequence_RelStructure pathLinksInSequence;
    protected TransferRefs_RelStructure transfers;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link PathLinkEndStructure }
     *     
     */
    public PathLinkEndStructure getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathLinkEndStructure }
     *     
     */
    public void setFrom(PathLinkEndStructure value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link PathLinkEndStructure }
     *     
     */
    public PathLinkEndStructure getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathLinkEndStructure }
     *     
     */
    public void setTo(PathLinkEndStructure value) {
        this.to = value;
    }

    /**
     * Gets the value of the accessibilityAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityAssessment }
     *     
     */
    public AccessibilityAssessment getAccessibilityAssessment() {
        return accessibilityAssessment;
    }

    /**
     * Sets the value of the accessibilityAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityAssessment }
     *     
     */
    public void setAccessibilityAssessment(AccessibilityAssessment value) {
        this.accessibilityAssessment = value;
    }

    /**
     * Gets the value of the accessModes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessModes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessModes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessModeEnumeration }
     * 
     * 
     */
    public List<AccessModeEnumeration> getAccessModes() {
        if (accessModes == null) {
            accessModes = new ArrayList<AccessModeEnumeration>();
        }
        return this.accessModes;
    }

    /**
     * Gets the value of the summaries property.
     * 
     * @return
     *     possible object is
     *     {@link AccessSummaries_RelStructure }
     *     
     */
    public AccessSummaries_RelStructure getSummaries() {
        return summaries;
    }

    /**
     * Sets the value of the summaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessSummaries_RelStructure }
     *     
     */
    public void setSummaries(AccessSummaries_RelStructure value) {
        this.summaries = value;
    }

    /**
     * Gets the value of the transferDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TransferDurationStructure }
     *     
     */
    public TransferDurationStructure getTransferDuration() {
        return transferDuration;
    }

    /**
     * Sets the value of the transferDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferDurationStructure }
     *     
     */
    public void setTransferDuration(TransferDurationStructure value) {
        this.transferDuration = value;
    }

    /**
     * Gets the value of the publicUse property.
     * 
     * @return
     *     possible object is
     *     {@link PublicUseEnumeration }
     *     
     */
    public PublicUseEnumeration getPublicUse() {
        return publicUse;
    }

    /**
     * Sets the value of the publicUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicUseEnumeration }
     *     
     */
    public void setPublicUse(PublicUseEnumeration value) {
        this.publicUse = value;
    }

    /**
     * Gets the value of the covered property.
     * 
     * @return
     *     possible object is
     *     {@link CoveredEnumeration }
     *     
     */
    public CoveredEnumeration getCovered() {
        return covered;
    }

    /**
     * Sets the value of the covered property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoveredEnumeration }
     *     
     */
    public void setCovered(CoveredEnumeration value) {
        this.covered = value;
    }

    /**
     * Gets the value of the gated property.
     * 
     * @return
     *     possible object is
     *     {@link GatedEnumeration }
     *     
     */
    public GatedEnumeration getGated() {
        return gated;
    }

    /**
     * Sets the value of the gated property.
     * 
     * @param value
     *     allowed object is
     *     {@link GatedEnumeration }
     *     
     */
    public void setGated(GatedEnumeration value) {
        this.gated = value;
    }

    /**
     * Gets the value of the lighting property.
     * 
     * @return
     *     possible object is
     *     {@link LightingEnumeration }
     *     
     */
    public LightingEnumeration getLighting() {
        return lighting;
    }

    /**
     * Sets the value of the lighting property.
     * 
     * @param value
     *     allowed object is
     *     {@link LightingEnumeration }
     *     
     */
    public void setLighting(LightingEnumeration value) {
        this.lighting = value;
    }

    /**
     * Gets the value of the allAreasWheelchairAccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllAreasWheelchairAccessible() {
        return allAreasWheelchairAccessible;
    }

    /**
     * Sets the value of the allAreasWheelchairAccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllAreasWheelchairAccessible(Boolean value) {
        this.allAreasWheelchairAccessible = value;
    }

    /**
     * Gets the value of the personCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonCapacity() {
        return personCapacity;
    }

    /**
     * Sets the value of the personCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonCapacity(BigInteger value) {
        this.personCapacity = value;
    }

    /**
     * Gets the value of the facilities property.
     * 
     * @return
     *     possible object is
     *     {@link SiteFacilitySets_RelStructure }
     *     
     */
    public SiteFacilitySets_RelStructure getFacilities() {
        return facilities;
    }

    /**
     * Sets the value of the facilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteFacilitySets_RelStructure }
     *     
     */
    public void setFacilities(SiteFacilitySets_RelStructure value) {
        this.facilities = value;
    }

    /**
     * Gets the value of the accessFeatureList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessFeatureList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessFeatureList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessFeatureEnumeration }
     * 
     * 
     */
    public List<AccessFeatureEnumeration> getAccessFeatureList() {
        if (accessFeatureList == null) {
            accessFeatureList = new ArrayList<AccessFeatureEnumeration>();
        }
        return this.accessFeatureList;
    }

    /**
     * Gets the value of the navigationType property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationTypeEnumeration }
     *     
     */
    public NavigationTypeEnumeration getNavigationType() {
        return navigationType;
    }

    /**
     * Sets the value of the navigationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationTypeEnumeration }
     *     
     */
    public void setNavigationType(NavigationTypeEnumeration value) {
        this.navigationType = value;
    }

    /**
     * Gets the value of the placesInSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PlacesInSequence_RelStructure }
     *     
     */
    public PlacesInSequence_RelStructure getPlacesInSequence() {
        return placesInSequence;
    }

    /**
     * Sets the value of the placesInSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacesInSequence_RelStructure }
     *     
     */
    public void setPlacesInSequence(PlacesInSequence_RelStructure value) {
        this.placesInSequence = value;
    }

    /**
     * Gets the value of the pathLinksInSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PathLinksInSequence_RelStructure }
     *     
     */
    public PathLinksInSequence_RelStructure getPathLinksInSequence() {
        return pathLinksInSequence;
    }

    /**
     * Sets the value of the pathLinksInSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathLinksInSequence_RelStructure }
     *     
     */
    public void setPathLinksInSequence(PathLinksInSequence_RelStructure value) {
        this.pathLinksInSequence = value;
    }

    /**
     * Gets the value of the transfers property.
     * 
     * @return
     *     possible object is
     *     {@link TransferRefs_RelStructure }
     *     
     */
    public TransferRefs_RelStructure getTransfers() {
        return transfers;
    }

    /**
     * Sets the value of the transfers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferRefs_RelStructure }
     *     
     */
    public void setTransfers(TransferRefs_RelStructure value) {
        this.transfers = value;
    }

}
