//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for POINT OF INTEREST CLASSIFICATION VIEW.
 * 
 * <p>Java class for PointOfInterestClassification_DerivedViewStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointOfInterestClassification_DerivedViewStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}DerivedViewStructure">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.netex.org.uk/netex}PointOfInterestClassificationRef" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.netex.org.uk/netex}MultilingualString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointOfInterestClassification_DerivedViewStructure", propOrder = {
    "pointOfInterestClassificationRef",
    "name"
})
public class PointOfInterestClassification_DerivedViewStructure
    extends DerivedViewStructure
{

    @XmlElement(name = "PointOfInterestClassificationRef")
    protected PointOfInterestClassificationRefStructure pointOfInterestClassificationRef;
    @XmlElement(name = "Name")
    protected MultilingualString name;

    /**
     * Gets the value of the pointOfInterestClassificationRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfInterestClassificationRefStructure }
     *     
     */
    public PointOfInterestClassificationRefStructure getPointOfInterestClassificationRef() {
        return pointOfInterestClassificationRef;
    }

    /**
     * Sets the value of the pointOfInterestClassificationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfInterestClassificationRefStructure }
     *     
     */
    public void setPointOfInterestClassificationRef(PointOfInterestClassificationRefStructure value) {
        this.pointOfInterestClassificationRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setName(MultilingualString value) {
        this.name = value;
    }

}
