//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for QUAY.
 * 
 * <p>Java class for Quay_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Quay_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}StopPlaceSpace_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}QuayGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Quay_VersionStructure", propOrder = {
    "publicCode",
    "plateCode",
    "shortCode",
    "destinations",
    "compassBearing",
    "compassOctant",
    "quayType",
    "parentQuayRef",
    "boardingPositions"
})
@XmlSeeAlso({
    Quay.class
})
@MappedSuperclass
public class Quay_VersionStructure
    extends StopPlaceSpace_VersionStructure
{

    @XmlElement(name = "PublicCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String publicCode;

    @XmlElement(name = "PlateCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String plateCode;

    @XmlElement(name = "ShortCode")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger shortCode;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<DestinationDisplayView> destinations;
    //protected DestinationDisplayViews_RelStructure destinations;

    @XmlElement(name = "CompassBearing")
    @Transient
    protected Float compassBearing;

    @XmlElement(name = "CompassOctant")
    @XmlSchemaType(name = "string")
    @Enumerated(EnumType.STRING)
    protected CompassBearing8Enumeration compassOctant;

    @XmlElement(name = "QuayType")
    @XmlSchemaType(name = "string")
    @Enumerated(EnumType.STRING)
    protected QuayTypeEnumeration quayType;

    @XmlElement(name = "ParentQuayRef")
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    protected QuayReference parentQuayRef;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    private final List<BoardingPosition> boardingPositions = new ArrayList<>();
    //protected BoardingPositions_RelStructure boardingPositions;

    /**
     * Gets the value of the publicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicCode() {
        return publicCode;
    }

    /**
     * Sets the value of the publicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicCode(String value) {
        this.publicCode = value;
    }

    /**
     * Gets the value of the plateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateCode() {
        return plateCode;
    }

    /**
     * Sets the value of the plateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateCode(String value) {
        this.plateCode = value;
    }

    /**
     * Gets the value of the shortCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShortCode() {
        return shortCode;
    }

    /**
     * Sets the value of the shortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShortCode(BigInteger value) {
        this.shortCode = value;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationDisplayViews_RelStructure }
     *     
     */
 /*   public DestinationDisplayViews_RelStructure getDestinations() {
        return destinations;
    }
*/
    /**
     * Sets the value of the destinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationDisplayViews_RelStructure }
     *     
     */
 //   public void setDestinations(DestinationDisplayViews_RelStructure value) {
 //       this.destinations = value;
 //   }

    /**
     * Gets the value of the compassBearing property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCompassBearing() {
        return compassBearing;
    }

    /**
     * Sets the value of the compassBearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCompassBearing(Float value) {
        this.compassBearing = value;
    }

    /**
     * Gets the value of the compassOctant property.
     * 
     * @return
     *     possible object is
     *     {@link CompassBearing8Enumeration }
     *     
     */
    public CompassBearing8Enumeration getCompassOctant() {
        return compassOctant;
    }

    /**
     * Sets the value of the compassOctant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompassBearing8Enumeration }
     *     
     */
    public void setCompassOctant(CompassBearing8Enumeration value) {
        this.compassOctant = value;
    }

    /**
     * Gets the value of the quayType property.
     * 
     * @return
     *     possible object is
     *     {@link QuayTypeEnumeration }
     *     
     */
    public QuayTypeEnumeration getQuayType() {
        return quayType;
    }

    /**
     * Sets the value of the quayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuayTypeEnumeration }
     *     
     */
    public void setQuayType(QuayTypeEnumeration value) {
        this.quayType = value;
    }

    /**
     * Gets the value of the parentQuayRef property.
     * 
     * @return
     *     possible object is
     *     {@link QuayReference }
     *     
     */
    public QuayReference getParentQuayRef() {
        return parentQuayRef;
    }

    /**
     * Sets the value of the parentQuayRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuayReference }
     *     
     */
    public void setParentQuayRef(QuayReference value) {
        this.parentQuayRef = value;
    }

    public List<DestinationDisplayView> getDestinations() {
        return destinations;
    }

    public void setDestinations(List<DestinationDisplayView> destinations) {
        this.destinations = destinations;
    }

    public List<BoardingPosition> getBoardingPositions() {
        return boardingPositions;
    }


    /**
     * Gets the value of the boardingPositions property.
     * 
     * @return
     *     possible object is
     *     {@link BoardingPositions_RelStructure }
     *     
     */
   /* public BoardingPositions_RelStructure getBoardingPositions() {
        return boardingPositions;
    }*

    /**
     * Sets the value of the boardingPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardingPositions_RelStructure }
     *     
     */
   /* public void setBoardingPositions(BoardingPositions_RelStructure value) {
        this.boardingPositions = value;
    }*/

}
