//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * SERVICE FACILITY SETs associated with entity.
 * 
 * <p>Java class for serviceFacilitySets_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serviceFacilitySets_RelStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}containmentAggregationStructure">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.netex.org.uk/netex}ServiceFacilitySetRef"/>
 *         &lt;element ref="{http://www.netex.org.uk/netex}ServiceFacilitySet"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceFacilitySets_RelStructure", propOrder = {
    "serviceFacilitySetRefOrServiceFacilitySet"
})
public class ServiceFacilitySets_RelStructure
    extends ContainmentAggregationStructure
{

    @XmlElements({
        @XmlElement(name = "ServiceFacilitySetRef", type = ServiceFacilitySetRefStructure.class),
        @XmlElement(name = "ServiceFacilitySet", type = ServiceFacilitySet.class)
    })
    protected List<Object> serviceFacilitySetRefOrServiceFacilitySet;

    /**
     * Gets the value of the serviceFacilitySetRefOrServiceFacilitySet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceFacilitySetRefOrServiceFacilitySet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceFacilitySetRefOrServiceFacilitySet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceFacilitySetRefStructure }
     * {@link ServiceFacilitySet }
     * 
     * 
     */
    public List<Object> getServiceFacilitySetRefOrServiceFacilitySet() {
        if (serviceFacilitySetRefOrServiceFacilitySet == null) {
            serviceFacilitySetRefOrServiceFacilitySet = new ArrayList<Object>();
        }
        return this.serviceFacilitySetRefOrServiceFacilitySet;
    }

}
