//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a list of ENTRANCEs.
 * 
 * <p>Java class for siteEntrances_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="siteEntrances_RelStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}containmentAggregationStructure">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.netex.org.uk/netex}EntranceRef"/>
 *         &lt;element ref="{http://www.netex.org.uk/netex}Entrance"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "siteEntrances_RelStructure", propOrder = {
    "entranceRefOrEntrance"
})
public class SiteEntrances_RelStructure
    extends ContainmentAggregationStructure
{

    @XmlElementRefs({
        @XmlElementRef(name = "EntranceRef", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Entrance", namespace = "http://www.netex.org.uk/netex", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> entranceRefOrEntrance;

    /**
     * Gets the value of the entranceRefOrEntrance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entranceRefOrEntrance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntranceRefOrEntrance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link VehicleEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ParkingEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link StopPlaceEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link ParkingEntranceForVehiclesRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link StopPlaceEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link VehicleEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link PointOfInterestEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link PointOfInterestVehicleEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ParkingEntranceForVehicles }{@code >}
     * {@link JAXBElement }{@code <}{@link ParkingPassengerEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link StopPlaceVehicleEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link PointOfInterestEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link StopPlaceVehicleEntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link EntranceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link PointOfInterestVehicleEntrance }{@code >}
     * {@link JAXBElement }{@code <}{@link SiteEntrance_VersionStructure }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getEntranceRefOrEntrance() {
        if (entranceRefOrEntrance == null) {
            entranceRefOrEntrance = new ArrayList<JAXBElement<?>>();
        }
        return this.entranceRefOrEntrance;
    }

}
