//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for SITE ENTRANCe.
 * 
 * <p>Java class for SiteEntrance_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SiteEntrance_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}SiteComponent_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}SiteEntranceGroup"/>
 *         &lt;group ref="{http://www.netex.org.uk/netex}ExternalEntranceGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SiteEntrance_VersionStructure", propOrder = {
    "publicCode",
    "label",
    "entranceType",
    "isExternal",
    "isEntry",
    "isExit",
    "width",
    "height",
    "droppedKerbOutside",
    "dropOffPointClose"
})
@XmlSeeAlso({
    ParkingPassengerEntrance_VersionStructure.class,
    StopPlaceEntrance_VersionStructure.class,
    PointOfInterestEntrance_VersionStructure.class,
    VehicleEntrance_VersionStructure.class,
    PointOfInterestVehicleEntrance_VersionStructure.class,
    ParkingEntranceForVehicles__VersionStructure.class
})
public class SiteEntrance_VersionStructure
    extends SiteComponent_VersionStructure
{

    @XmlElement(name = "PublicCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String publicCode;
    @XmlElement(name = "Label")
    protected MultilingualString label;
    @XmlElement(name = "EntranceType")
    @XmlSchemaType(name = "string")
    protected EntranceEnumeration entranceType;
    @XmlElement(name = "IsExternal", defaultValue = "true")
    protected Boolean isExternal;
    @XmlElement(name = "IsEntry", defaultValue = "true")
    protected Boolean isEntry;
    @XmlElement(name = "IsExit", defaultValue = "true")
    protected Boolean isExit;
    @XmlElement(name = "Width")
    protected BigDecimal width;
    @XmlElement(name = "Height")
    protected BigDecimal height;
    @XmlElement(name = "DroppedKerbOutside")
    protected Boolean droppedKerbOutside;
    @XmlElement(name = "DropOffPointClose")
    protected Boolean dropOffPointClose;

    /**
     * Gets the value of the publicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicCode() {
        return publicCode;
    }

    /**
     * Sets the value of the publicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicCode(String value) {
        this.publicCode = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setLabel(MultilingualString value) {
        this.label = value;
    }

    /**
     * Gets the value of the entranceType property.
     * 
     * @return
     *     possible object is
     *     {@link EntranceEnumeration }
     *     
     */
    public EntranceEnumeration getEntranceType() {
        return entranceType;
    }

    /**
     * Sets the value of the entranceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntranceEnumeration }
     *     
     */
    public void setEntranceType(EntranceEnumeration value) {
        this.entranceType = value;
    }

    /**
     * Gets the value of the isExternal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsExternal() {
        return isExternal;
    }

    /**
     * Sets the value of the isExternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExternal(Boolean value) {
        this.isExternal = value;
    }

    /**
     * Gets the value of the isEntry property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEntry() {
        return isEntry;
    }

    /**
     * Sets the value of the isEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEntry(Boolean value) {
        this.isEntry = value;
    }

    /**
     * Gets the value of the isExit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsExit() {
        return isExit;
    }

    /**
     * Sets the value of the isExit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExit(Boolean value) {
        this.isExit = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWidth(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeight(BigDecimal value) {
        this.height = value;
    }

    /**
     * Gets the value of the droppedKerbOutside property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDroppedKerbOutside() {
        return droppedKerbOutside;
    }

    /**
     * Sets the value of the droppedKerbOutside property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDroppedKerbOutside(Boolean value) {
        this.droppedKerbOutside = value;
    }

    /**
     * Gets the value of the dropOffPointClose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDropOffPointClose() {
        return dropOffPointClose;
    }

    /**
     * Sets the value of the dropOffPointClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropOffPointClose(Boolean value) {
        this.dropOffPointClose = value;
    }

}
