//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package uk.org.netex.netex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for VERSIONED CHILD.
 * 
 * <p>Java class for VersionedChildStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionedChildStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}EntityInVersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}VersionedChildGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionedChildStructure", propOrder = {
    "extensions"
})
@XmlSeeAlso({
    ResponsibilityRoleAssignment_VersionedChildStructure.class,
    GroupConstraintMember_VersionedChildStructure.class,
    AccessibilityAssessment_VersionedChildStructure.class,
    FlexiblePointProperties_VersionedChildStructure.class,
    VehicleQuayAlignment_VersionStructure.class,
    StairFlight_VersionedChildStructure.class,
    OnboardStay_VersionedChlldStructure.class,
    CodespaceAssignment_VersionedChildStructure.class,
    TrainInCompoundTrain_VersionedChildStructure.class,
    AbstractGroupMember_VersionedChildStructure.class,
    PointOnLink_VersionedChildStructure.class,
    Via_VersionedChildStructure.class,
    VehiclePositionAlignment_VersionStructure.class,
    TopographicPlaceDescriptor_VersionedChildStructure.class,
    PointOfInterestClassificationHierarchyMemberStructure.class,
    Accommodation_VersionedChildStructure.class,
    LinkInLinkSequence_VersionedChildStructure.class,
    ParkingCapacity_VersionedChildStructure.class,
    SchematicMapMember_VersionedChildStructure.class,
    ParkingProperties_VersionedChildStructure.class,
    JourneyTiming_VersionedChildStructure.class,
    FlexibleLinkProperties_VersionedChildStructure.class,
    PointInLinkSequence_VersionedChildStructure.class,
    AccessSummary_VersionedChildStructure.class,
    AccessibilityLimitation_VersionedChildStructure.class,
    UserNeed_VersionedChildStructure.class,
    AlternativeName_VersionedChildStructure.class
})
public class VersionedChildStructure
    extends EntityInVersionStructure
{

    @XmlElement(name = "Extensions")
    protected ExtensionsStructure extensions;

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsStructure }
     *     
     */
    public ExtensionsStructure getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsStructure }
     *     
     */
    public void setExtensions(ExtensionsStructure value) {
        this.extensions = value;
    }

}
