//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DayEventEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DayEventEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="anyDay"/>
 *     &lt;enumeration value="normalDay"/>
 *     &lt;enumeration value="marketDay"/>
 *     &lt;enumeration value="matchDay"/>
 *     &lt;enumeration value="eventDay"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DayEventEnumeration")
@XmlEnum
public enum DayEventEnumeration {

    @XmlEnumValue("anyDay")
    ANY_DAY("anyDay"),
    @XmlEnumValue("normalDay")
    NORMAL_DAY("normalDay"),
    @XmlEnumValue("marketDay")
    MARKET_DAY("marketDay"),
    @XmlEnumValue("matchDay")
    MATCH_DAY("matchDay"),
    @XmlEnumValue("eventDay")
    EVENT_DAY("eventDay");
    private final String value;

    DayEventEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DayEventEnumeration fromValue(String v) {
        for (DayEventEnumeration c: DayEventEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
