//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 10:37:32 AM CET 
//


package no.rutebanken.tiamat.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a list of PATH JUNCTIONs.
 * 
 * <p>Java class for pathJunctions_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pathJunctions_RelStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}containmentAggregationStructure">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.netex.org.uk/netex}PathJunctionRef"/>
 *         &lt;element ref="{http://www.netex.org.uk/netex}PathJunction"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pathJunctions_RelStructure", propOrder = {
    "pathJunctionRefOrPathJunction"
})
@Entity
public class PathJunctions_RelStructure
    extends ContainmentAggregationStructure
{

    @XmlElements({
        @XmlElement(name = "PathJunctionRef", type = PathJunctionRefStructure.class),
        @XmlElement(name = "PathJunction", type = PathJunction.class)
    })
    @ElementCollection(targetClass=PathJunctionRefStructure.class)

    protected List<PathJunctionRefStructure> pathJunctionRefOrPathJunction;

    /**
     * Gets the value of the pathJunctionRefOrPathJunction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathJunctionRefOrPathJunction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathJunctionRefOrPathJunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PathJunctionRefStructure }
     * {@link PathJunction }
     * 
     * 
     */
    public List<PathJunctionRefStructure> getPathJunctionRefOrPathJunction() {
        if (pathJunctionRefOrPathJunction == null) {
            pathJunctionRefOrPathJunction = new ArrayList<>();
        }
        return this.pathJunctionRefOrPathJunction;
    }

}
