//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a PLACE.
 * 
 * <p>Java class for Place_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Place_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}Zone_VersionStructure">
 *       &lt;group ref="{http://www.netex.org.uk/netex}PlaceGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Place_VersionStructure", propOrder = {
    "placeTypes"
})
@XmlSeeAlso({
    EquipmentPlace_VersionStructure.class,
    Address_VersionStructure.class,
    FlexibleStopPlace_VersionStructure.class,
    TopographicPlace_VersionStructure.class,
    FlexibleQuay_VersionStructure.class,
    AddressablePlace_VersionStructure.class,
    Country_VersionStructure.class
})
public abstract class Place_VersionStructure
    extends Zone_VersionStructure
{

    protected TypeOfPlaceRefs_RelStructure placeTypes;

    public Place_VersionStructure(){}

    public Place_VersionStructure(MultilingualString name) {
        super(name);
    }

    /**
     * Gets the value of the placeTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfPlaceRefs_RelStructure }
     *     
     */
    public TypeOfPlaceRefs_RelStructure getPlaceTypes() {
        return placeTypes;
    }

    /**
     * Sets the value of the placeTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfPlaceRefs_RelStructure }
     *     
     */
    public void setPlaceTypes(TypeOfPlaceRefs_RelStructure value) {
        this.placeTypes = value;
    }

}
