//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a POINT OF INTEREST SPACE.
 * 
 * <p>Java class for PointOfInterestSpace_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointOfInterestSpace_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}PointOfInterestComponent_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}PointOfInterestSpaceGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointOfInterestSpace_VersionStructure", propOrder = {
    "accessSpaceType",
    "pointOfInterestSpaceType",
    "passageType",
    "parentPointOfInterestSpaceRef",
    "entrances"
})
@XmlSeeAlso({
    PointOfInterestSpace.class
})
public class PointOfInterestSpace_VersionStructure
    extends PointOfInterestComponent_VersionStructure
{

    @XmlElement(name = "AccessSpaceType")
    protected AccessSpaceTypeEnumeration accessSpaceType;
    @XmlElement(name = "PointOfInterestSpaceType")
    @XmlSchemaType(name = "string")
    protected PointOfInterestSpaceTypeEnumeration pointOfInterestSpaceType;
    @XmlElement(name = "PassageType")
    @XmlSchemaType(name = "string")
    protected PassageTypeEnumeration passageType;
    @XmlElement(name = "ParentPointOfInterestSpaceRef")
    protected PointOfInterestSpaceRefStructure parentPointOfInterestSpaceRef;
    protected PointOfInterestEntrances_RelStructure entrances;

    /**
     * Gets the value of the accessSpaceType property.
     * 
     * @return
     *     possible object is
     *     {@link AccessSpaceTypeEnumeration }
     *     
     */
    public AccessSpaceTypeEnumeration getAccessSpaceType() {
        return accessSpaceType;
    }

    /**
     * Sets the value of the accessSpaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessSpaceTypeEnumeration }
     *     
     */
    public void setAccessSpaceType(AccessSpaceTypeEnumeration value) {
        this.accessSpaceType = value;
    }

    /**
     * Gets the value of the pointOfInterestSpaceType property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfInterestSpaceTypeEnumeration }
     *     
     */
    public PointOfInterestSpaceTypeEnumeration getPointOfInterestSpaceType() {
        return pointOfInterestSpaceType;
    }

    /**
     * Sets the value of the pointOfInterestSpaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfInterestSpaceTypeEnumeration }
     *     
     */
    public void setPointOfInterestSpaceType(PointOfInterestSpaceTypeEnumeration value) {
        this.pointOfInterestSpaceType = value;
    }

    /**
     * Gets the value of the passageType property.
     * 
     * @return
     *     possible object is
     *     {@link PassageTypeEnumeration }
     *     
     */
    public PassageTypeEnumeration getPassageType() {
        return passageType;
    }

    /**
     * Sets the value of the passageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassageTypeEnumeration }
     *     
     */
    public void setPassageType(PassageTypeEnumeration value) {
        this.passageType = value;
    }

    /**
     * Gets the value of the parentPointOfInterestSpaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfInterestSpaceRefStructure }
     *     
     */
    public PointOfInterestSpaceRefStructure getParentPointOfInterestSpaceRef() {
        return parentPointOfInterestSpaceRef;
    }

    /**
     * Sets the value of the parentPointOfInterestSpaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfInterestSpaceRefStructure }
     *     
     */
    public void setParentPointOfInterestSpaceRef(PointOfInterestSpaceRefStructure value) {
        this.parentPointOfInterestSpaceRef = value;
    }

    /**
     * Gets the value of the entrances property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfInterestEntrances_RelStructure }
     *     
     */
    public PointOfInterestEntrances_RelStructure getEntrances() {
        return entrances;
    }

    /**
     * Sets the value of the entrances property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfInterestEntrances_RelStructure }
     *     
     */
    public void setEntrances(PointOfInterestEntrances_RelStructure value) {
        this.entrances = value;
    }

}
