//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for SUITABILITY.
 * 
 * <p>Java class for Suitability_VersionedChildStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Suitability_VersionedChildStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}UserNeed_VersionedChildStructure">
 *       &lt;sequence>
 *         &lt;element name="Suitable" type="{http://www.netex.org.uk/netex}SuitableEnumeration"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suitability_VersionedChildStructure", propOrder = {
    "suitable"
})
@XmlSeeAlso({
    Suitability.class
})
public class Suitability_VersionedChildStructure
    extends UserNeed_VersionedChildStructure
{

    @XmlElement(name = "Suitable", required = true)
    @XmlSchemaType(name = "NMTOKEN")
    protected SuitableEnumeration suitable;

    /**
     * Gets the value of the suitable property.
     * 
     * @return
     *     possible object is
     *     {@link SuitableEnumeration }
     *     
     */
    public SuitableEnumeration getSuitable() {
        return suitable;
    }

    /**
     * Sets the value of the suitable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuitableEnumeration }
     *     
     */
    public void setSuitable(SuitableEnumeration value) {
        this.suitable = value;
    }

}
