//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of one or more VALIDITY PARAMETERs.
 * 
 * <p>Java class for validityRuleParameters_RelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validityRuleParameters_RelStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}containmentAggregationStructure">
 *       &lt;sequence>
 *         &lt;element name="ValidityRuleParameter" type="{http://www.netex.org.uk/netex}ValidityRuleParameter_VersionStructure" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validityRuleParameters_RelStructure", propOrder = {
    "validityRuleParameter"
})
public class ValidityRuleParameters_RelStructure
    extends ContainmentAggregationStructure
{

    @XmlElement(name = "ValidityRuleParameter", required = true)
    protected List<ValidityRuleParameter_VersionStructure> validityRuleParameter;

    /**
     * Gets the value of the validityRuleParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validityRuleParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidityRuleParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidityRuleParameter_VersionStructure }
     * 
     * 
     */
    public List<ValidityRuleParameter_VersionStructure> getValidityRuleParameter() {
        if (validityRuleParameter == null) {
            validityRuleParameter = new ArrayList<ValidityRuleParameter_VersionStructure>();
        }
        return this.validityRuleParameter;
    }

}
