//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:41:01 PM CET 
//


package no.rutebanken.tiamat.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for Waiting EQUIPMENT.
 * 
 * <p>Java class for WaitingEquipment_VersionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaitingEquipment_VersionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}SiteEquipment_VersionStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.netex.org.uk/netex}WaitingEquipmentGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaitingEquipment_VersionStructure", propOrder = {
    "seats",
    "width",
    "length",
    "stepFree",
    "wheelchairAreaWidth",
    "wheelchairAreaLength",
    "smokingAllowed",
    "heated",
    "airConditioned"
})
@XmlSeeAlso({
    WaitingEquipment.class,
    SeatingEquipment_VersionStructure.class,
    WaitingRoomEquipment_VersionStructure.class,
    ShelterEquipment_VersionStructure.class
})
public abstract class WaitingEquipment_VersionStructure
    extends SiteEquipment_VersionStructure
{

    @XmlElement(name = "Seats")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger seats;
    @XmlElement(name = "Width")
    protected BigDecimal width;
    @XmlElement(name = "Length")
    protected BigDecimal length;
    @XmlElement(name = "StepFree")
    protected Boolean stepFree;
    @XmlElement(name = "WheelchairAreaWidth")
    protected BigDecimal wheelchairAreaWidth;
    @XmlElement(name = "WheelchairAreaLength")
    protected BigDecimal wheelchairAreaLength;
    @XmlElement(name = "SmokingAllowed")
    protected Boolean smokingAllowed;
    @XmlElement(name = "Heated", defaultValue = "false")
    protected Boolean heated;
    @XmlElement(name = "AirConditioned", defaultValue = "false")
    protected Boolean airConditioned;

    /**
     * Gets the value of the seats property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeats() {
        return seats;
    }

    /**
     * Sets the value of the seats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeats(BigInteger value) {
        this.seats = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWidth(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

    /**
     * Gets the value of the stepFree property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStepFree() {
        return stepFree;
    }

    /**
     * Sets the value of the stepFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStepFree(Boolean value) {
        this.stepFree = value;
    }

    /**
     * Gets the value of the wheelchairAreaWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWheelchairAreaWidth() {
        return wheelchairAreaWidth;
    }

    /**
     * Sets the value of the wheelchairAreaWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWheelchairAreaWidth(BigDecimal value) {
        this.wheelchairAreaWidth = value;
    }

    /**
     * Gets the value of the wheelchairAreaLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWheelchairAreaLength() {
        return wheelchairAreaLength;
    }

    /**
     * Sets the value of the wheelchairAreaLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWheelchairAreaLength(BigDecimal value) {
        this.wheelchairAreaLength = value;
    }

    /**
     * Gets the value of the smokingAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmokingAllowed() {
        return smokingAllowed;
    }

    /**
     * Sets the value of the smokingAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmokingAllowed(Boolean value) {
        this.smokingAllowed = value;
    }

    /**
     * Gets the value of the heated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHeated() {
        return heated;
    }

    /**
     * Sets the value of the heated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHeated(Boolean value) {
        this.heated = value;
    }

    /**
     * Gets the value of the airConditioned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirConditioned() {
        return airConditioned;
    }

    /**
     * Sets the value of the airConditioned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirConditioned(Boolean value) {
        this.airConditioned = value;
    }

}
