DROP TABLE vehicle_stopping_places_rel_structure;
DROP SEQUENCE vehicle_stopping_places_rel_structure_seq;


DROP TABLE explicit_equipments_rel_structure;
DROP SEQUENCE explicit_equipments_rel_structure_seq;

