ALTER TABLE access_space ADD COLUMN url VARCHAR(2048);
ALTER TABLE boarding_position ADD COLUMN url VARCHAR(2048);
ALTER TABLE parking ADD COLUMN url VARCHAR(2048);
ALTER TABLE parking_area ADD COLUMN url VARCHAR(2048);
ALTER TABLE quay ADD COLUMN url VARCHAR(2048);
ALTER TABLE stop_place ADD COLUMN url VARCHAR(2048);
