CREATE TABLE async_stop_place_job
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reason      TEXT,
    created_ids TEXT[],
    status      INTEGER,
    PRIMARY KEY (id)
);

ALTER TABLE async_stop_place_job OWNER TO tiamat;