pubsub_project = "ent-tiamat-dev"
storage_project = "ent-tiamat-dev"
cloudsql_project="ent-tiamat-dev"
kube_namespace = "tiamat"
bucket_instance_suffix = "dev"
location = "europe-west1"
bucket_instance_prefix="ror-tiamat-gcp2"
db_tier="db-custom-2-7680"
